FROM nvidia/cuda:9.0-devel-centos7
MAINTAINER h2oai "h2o.ai"

ARG JENKINS_UID='2117'
ARG JENKINS_GID='2117'
ARG H2O_BRANCH='h2o3'
ARG PYTHON_VERSIONS='3.5,3.6'

RUN \
    curl -s https://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo | sed 's/\$releasever/6/g' > /etc/yum.repos.d/epel-apache-maven.repo && \
    yum install -y centos-release-scl && \
    yum install -y devtoolset-4-toolchain python27 python33-python-virtualenv zip java-1.8.0-openjdk-devel apache-maven wget git unzip make

# Install Python versions above
COPY xgb_build/scripts/install_python_version_centos /usr/sbin/
RUN \
    chmod a+x /usr/sbin/install_python_version_centos && \
    sync && \
    /usr/sbin/install_python_version_centos

ENV CMAKE_VERSION '3.18'
ENV CMAKE_PATCH '.2'
RUN \
    # Check that gcc is of correct version
    source scl_source enable devtoolset-4 && \
    if [ "$(gcc --version | head -1)" != 'gcc (GCC) 5.3.1 20160406 (Red Hat 5.3.1-6)' ]; then exit 1; fi && \
    # Install CMake
    wget http://www.cmake.org/files/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}.${CMAKE_PACH}.tar.gz && \
    tar -xvzf cmake-${CMAKE_VERSION}.${CMAKE_PACH}.tar.gz && \
    cd cmake-${CMAKE_VERSION}.${CMAKE_PACH}/ && \
    ./configure && \
    make && \
    make install && \
    cd .. && \
    rm -rf cmake-${CMAKE_VERSION}.${CMAKE_PACH} && \
    if [ "$(cmake --version | head -1)" != 'cmake version ${CMAKE_VERSION}.${CMAKE_PACH}' ]; then exit 1; fi

# Add the Jenkins user
RUN \
    groupadd -g ${JENKINS_GID} jenkins && \
    useradd jenkins -m -u ${JENKINS_UID} -g jenkins

# Install Python 3.7 and 3.8
COPY xgb_build/scripts/Setup.dist.patched /usr/src/
COPY xgb_build/scripts/install_python_source_centos /usr/sbin/
RUN \
    yum install -y xz libffi-devel bzip2-devel ncurses-devel gdbm-devel xz-devel sqlite-devel readline-devel zlib-devel libuuid-devel && \
    yum groupinstall -y 'Development Tools' && \
    cd /usr/src && \
    curl -LO 'https://www.openssl.org/source/openssl-1.1.0h.tar.gz' && \
    tar -xf openssl-1.1.0h.tar.gz && \
    cd openssl-1.1.0h && \
    ./config shared --prefix=/usr/local/openssl11 --openssldir=/usr/local/openssl11 && \
    make && \
    make install && \
    cd .. && \
    rm -rf openssl-1.1.0h* && \
    chmod a+x /usr/sbin/install_python_source_centos && \
    sync && \
    /usr/sbin/install_python_source_centos 3.7.0 /usr/src/Setup.dist.patched && \
    /usr/sbin/install_python_source_centos 3.8.0
